### ISSUE TITLE
SSL error for https://mvp.kablamo.org

### ISSUE THREAD

**Issue by kablamo** [kablamo/mvp.kablamo.org#11]
Browser complains the connection is not private when visiting https://mvp.kablamo.org/
Reported here: https://twitter.com/keithbro/status/943693262023303168

I'm using github pages and the [docs](https://help.github.com/articles/securing-your-github-pages-site-with-https/) say I can't enable ssl there unless I use the github.io domain (vs mvp.kablamo.org).  I should host it on my own server.  I'm thinking this is lower priority since the content is not particularly sensitive.

**Comment by naltun** [comment]
For whatever reason, when I follow your link above, the accordion menus on the navbar cease working, and every menu is expanded by default. When I visit mvp.kablamo.org by typing it in, the menus work. 

Not sure why that happens. :man_shrugging:

**Comment by kablamo** [comment]
that happens because jquery is not downloading you use https.  works for vanilla http.  not sure exactly why but its related and some security header i'm sure

**Comment by Grinnz** [comment]
It's because you're requesting jquery over plain HTTP. Change it to https and it should work for both.

**Comment by kablamo** [comment]
:man_facepalming:   Arrrg!  Thank you @Grinnz, I can't believe I didn't notice that.  So happy to have ssl now.
