### ISSUE TITLE
Unique page titles for each url path

### ISSUE THREAD

**Issue by laurengarcia** [kablamo/mvp.kablamo.org#16]
This is so awesome, thanks for writing this. Am queuing it up so I can browse it offline on the plane today and noticed that all the page titles are identical -- would be nice to make those unique to give user a hand in navigating (and to boost your SEO).

**Comment by kablamo** [comment]
Thanks Lauren!  I'll fix that.  I'm curious how you are reading it offline?  Pocket?

**Comment by kablamo** [comment]
Fixed
