### ISSUE TITLE
Mention File::Slurper

### ISSUE THREAD

**Issue by Grinnz** [kablamo/mvp.kablamo.org#19]
(Sorry accidentally submitted before writing the description)

I think the Working with Files section you just [blogged](http://blog.kablamo.org/2018/04/03/files/) is great, but there's one thing missing. File::Slurper should be mentioned, both on its own and as a replacement for File::Slurp that fixes both its technical and interface/usability issues. You might also mention that Path::Tiny has a good interface for this as well so can also be considered a good replacement for File::Slurp. (though it encompasses many of the low-level modules you list, so maybe it doesn't need to be mentioned specifically)

**Comment by kablamo** [comment]
Thanks!  I agree. Those are awesome suggestions.  I will make those changes.

I never really understood why people use File::Slurper directly in their code.  The ui for Path::Tiny or IO::All is simpler.  I guess people like it if they prefer working with bare metal open/close and want/need to keep the number of dependencies low.

**Comment by Grinnz** [comment]
Path::Tiny is definitely a good all around tool and is just as light on dependencies as all the lower level ones so practically I agree. But sometimes a program doesn't need to do anything with files other than slurp one in or write one out so File::Slurper is a more direct implementation of what you need. It's also easier to recommend as a replacement for File::Slurp since it does similar things (less docs to read, etc)

Unrelated note: I think your description of IO::All is a pretty good representation, but just adding my point of view. I don't use or recommend it because its overloading of operators is particularly odd and bug-prone -- the < and > operators are overloaded to do things that are completely antithetical to their normal purpose as a numerical comparison, which will be a problem if overloading is ever made more coercive.

**Comment by kablamo** [comment]
I did all of your suggestions.

**Comment by kablamo** [comment]
Thanks again for the feedback @Grinnz .  Your suggestions have been really helpful and your knowledge of Perl and Perl history are deeper than mine.  Are you interested in getting a draft of whatever I'm writing via email a few days before publication so you can review it and make suggestions?  If you don't have time on any given week you could just not respond.  The only thing I can offer in return is to put your name/link on the site somewhere.   Or we could just keep things as they are.  Either way thank you!

**Comment by Grinnz** [comment]
I'd be happy to review. You can send to dbook@cpan.org or my username at gmail.
