### ISSUE TITLE
Variables section needs to explain why @ and % become $

### ISSUE THREAD

**Issue by matthewpersico** [kablamo/mvp.kablamo.org#5]
Something like:

Notice how referencing individual elements of an array or a hash uses the scalar sigil, not the array or hash sigil respectively. This is because the sigil applies to the specific piece of data being accessed, not the source. foo is an array, hence @foo, foo[7] is a scalar, hence $foo[7].

**Comment by kablamo** [comment]
You are right.  Thats an oversight.  Some topics I am planning to write about at some point:
- Context
- Working with Arrays
- Workings with Hashes

I think at least one of those articles would address your concern.

**Comment by kablamo** [comment]
On second thought I decided there is more I can do now.

- https://github.com/kablamo/mvp.kablamo.org/commit/f14919a96aef16c980b40aee2130921eb79b1c98#diff-7e8539cd7296274a5ad6cb76e0eca9de
 - http://mvp.kablamo.org/basics/variables/
