### ISSUE TITLE
Exceptions page suggestions

### ISSUE THREAD

**Issue by Grinnz** [kablamo/mvp.kablamo.org#7]
Copied from my reddit comment.

Very nicely put together. I would suggest mentioning [Syntax::Keyword::Try](https://metacpan.org/pod/Syntax::Keyword::Try) as preferred over Try::Tiny when you are able to use it (it requires XS support and perl 5.14+). It does not suffer from many of the caveats of Try::Tiny, including the speed penalty.

Also, if you are going to document how to use raw eval, you should not include any 'if $@' tests, as that is fundamentally flawed (as the Try::Tiny docs note). Instead you should always make evals return 1, and check the return value to determine if an exception was thrown; when an exception is thrown, the eval returns undef.

(Common idiom for this: `unless (eval { ...; 1 }) { <do something with $@> }`)

**Comment by kablamo** [comment]
Thanks!  I recently discovered your Perl tutorial on learn x in y minutes and thought it was great.  Very similar to what I was trying to do with MVP.

1. `Syntax::Keyword::Try` looks awesome.  It seems to solve most of my complaints about `Try::Tiny`.  

2. Yuck.  I really don't want to `return 1` in my `eval` statements.  I've always liked `eval` over try/catch because its so concise.  I think 99% of the time `if $@` will be good enough.  But I can see your point that in order to be 100% sure you will always catch the exception you need to `return 1` and check the return value.  I'd rather use `Syntax::Keyword::Try` than the `return 1` idiom you suggest.  I'll have to think about this.  I'm not sure what the best way to handle this is in MVP.  It seems likely I should have a separate article about eval and a separate article about `Syntax::Keyword::Try`.

**Comment by Grinnz** [comment]
The idiom I usually use is just to have `1` as the last statement in the eval, the `return` keyword isn't needed. I agree it's not pretty but eval never has been, that's why these try/catch modules exist. As another note if you want to have in depth discussion of `eval` it's definitely worth linking to the BACKGROUND section of Try::Tiny's docs as that's one of the best discussions of eval's caveats.

**Comment by autarch** [comment]
You can do `if eval { foo(); 1 }`. No need for a `return`, at least.

**Comment by kablamo** [comment]
Thanks.  I do intend to fix these issues.

**Comment by kablamo** [comment]
I wanted to fix this so I reread the [Try::Tiny note](https://metacpan.org/pod/Try::Tiny#BACKGROUND) again.  But I don't understand the requirement to return 1.  Maybe it was necessary before Perl 5.14.0 and now its not?  Can you give an example of where not checking the return value causes problems?

**Comment by Grinnz** [comment]
die $false_object;

**Comment by Grinnz** [comment]
or, dying from a scope where $@ is localized.

**Comment by kablamo** [comment]
Whats a false object?  Modules that don't return 1 at the end get compile time errors in recent Perls.
```
use Foo; # dies here
eval { die Foo->new() };
```

I'd also love to see an example where `$@` is wiped out because it wasn't localized.  I tried to come up with an example but failed.

**Comment by Grinnz** [comment]
```
package Foo;
use overload bool => sub { 0 };
# or more plausible:
use overload '""' => sub { '' }, fallback => 1;

package main;
eval { die Foo->new };
if ($@) { # $@ is a false object

{ local $@; eval { die 'foo' }; }
if ($@) { # $@ has lost its value to localization
```

**Comment by kablamo** [comment]
Thanks.  

**1. False objects**
From your example, I can see the idiom `eval {...}; if ($@) { handle_error($@) }` doesn't work if the exception object evaluates to a false value.  I was tempted to suggest this as a better solution:
```
eval { die $false_object };
if (defined $@) {
    # handle error
}
```
But I think you will argue this doesn't handle the case where $false_object is undef.

**2. Localizing $@**
I get that localizing $@ doesn't work.  I'm trying to understand why I would be tempted to try localizing $@.  Are you aware of any examples?  Maybe this would be useful when writing code for exception objects?

**Comment by Grinnz** [comment]
1. It's not possible to get `$@` set undef accidentally, however, it's perfectly possible for (probably dumb) code to do it on purpose, as it's a global variable. The bigger issue is that `$@` is not undef when there is no error, it is an empty string, so that solution is incorrect to begin with.

2. Naive code attempting to prevent clobbering `$@` when running evals may cause this to occur (I have written such code!) Remember that unless you localize `$@` simply starting an `eval` will change the *global variable* for the whole process. This may not seem like a big deal but once you're several function calls and evals deep it can be, this is why Try::Tiny jumps through the hoops that it does (and Syntax::Keyword::Try less so, since it only has to work on 5.14+ where eval is less dumb). The correct-and-polite thing to do in module code is thus:

```
my ($errored, $error);
{
  local $@;
  unless (eval { ...; 1 }) {
    $errored = 1;
    $error = $@;
  }
}
if ($errored) {
  # die works normally in this scope, $@ is no longer localized, and your error is saved in $error
}
```

Oh yes, it's ugly, but that's why we have those try/catch modules to hide all of that for us :) (and they actually do a bit more with `$@` so it appears correct to the code inside the eval as well)

**Comment by kablamo** [comment]
I finally rewrote the exception handling stuff.   Its on the site but not linked up yet.  It would be great hear any feedback either of you might have.  These two articles would replace the single article that exists atm.
http://mvp.kablamo.org/builtins/die-eval/
http://mvp.kablamo.org/builtins/syntax-keyword-try/

**Comment by Grinnz** [comment]
I don't think `(no one actually does this because its too much typing)` needs to be included since it 1. isn't true (https://metacpan.org/source/DBOOK/Mojo-SQLite-3.000/lib/Mojo/SQLite/Database.pm#L61-74), and 2. discourages proper module writing (or suggests "it's ok to be lazy with eval"). I also still don't like that it shows examples of testing `$@` for truth at all, but I am satisfied as long as the better alternative of try/catch is presented. (The link to the try/catch page seems incorrect though, it links to localhost)

**Comment by autarch** [comment]
eval() parses, compiles, and evaluates a block of code at runtime and
catches any exceptions that are raised.

That's the string form of eval. The block form does not parse and compile
at runtime. It parses and compile at compile time and traps errors at run
time.

no one actually does this because its too much typing

Maybe you could say something like "but lots of authors either forget to do
this or don't bother because it's too tedious".

Syntax::Keyword::Try <https://metacpan.org/pod/Syntax::Keyword::Try> is
probably the best way to handle exceptions in Perl

Except that it breaks really useful tools like Perltidy and Perl::Critic.
But other than that, it's great ;)

Seriously, I'd love to use stuff like that but not being able to use tidy
and critic isn't worth not having to type a semi-colon. I'd recommend
Try::Tiny instead.

*2. A try block does not catch exceptions.* The catch block catches
exceptions.

Yes, that's how every other language works too. This is not a pitfall.

*1. A try block must be followed by catch or finally or both.*

Which is something that you don't have to deal with when using Try::Tiny.



Cheers,

Dave Rolsky
http://blog.urth.org
https://github.com/autarch

**Comment by Grinnz** [comment]
> Seriously, I'd love to use stuff like that but not being able to use tidy
and critic isn't worth not having to type a semi-colon.

I hope you don't think that's the only benefit of SKT. It also does not have the significant performance penalty and other side effects of Try::Tiny's sub wrappers (like un-block-like handling of `@_` and return, which is just as surprising as all of the eval effects it fixes).

**Comment by Grinnz** [comment]
Also, I just tried running perltidy and perlcritic (using the Freenode theme of course) on a project where I'm using Syntax::Keyword::Try, and it did not seem to have any issues, so it is possible.

**Comment by autarch** [comment]
Ah, that's good to know. I guess the syntax modification is so minor that
it doesn't break those tools.


Cheers,

Dave Rolsky
http://blog.urth.org
https://github.com/autarch

**Comment by kablamo** [comment]
Awesome, thanks to both of you for the feedback.  I will use your suggestions.

Btw you may find this twitter poll vaguely interesting: 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">How do you handle exceptions in Perl?</p>&mdash; Eric Johnson (@kablamo_) <a href="https://twitter.com/kablamo_/status/966307648621727745?ref_src=twsrc%5Etfw">February 21, 2018</a></blockquote>

@autarch :
> *2. A try block does not catch exceptions.* The catch block catches exceptions.
> *1. A try block must be followed by catch or finally or both.*

Both of these behaviors are how Java's try/catch works.  You are right these aren't really pitfalls.  I labeled that section "Pitfalls for Perl programmers" -- its for people who are used to die/eval and have forgotten how exceptions work.

**Comment by Grinnz** [comment]
> Btw you may find this twitter poll vaguely interesting:

One thing this poll shows is that Syntax::Keyword::Try needs more exposure! :smile:

**Comment by kablamo** [comment]
@Grinnz @autarch Just letting you know I wrote a third article about exceptions.  It reviews a bunch of different try/catch cpan modules and has some benchmarks.  I also tested Syntax::Keyword::Try with perlcritic and perltidy and didn't find any problems yet.  I plan to start releasing these articles on Tuesday morning.  Any feedback (before or after) is very welcome.  

Here is the article: http://mvp.kablamo.org/cpan/exceptions/

**Comment by Grinnz** [comment]
I like that page a lot! Very comprehensive and helpful.

I'll add that the more specific drawback of TryCatch is that it is based on Devel::Declare, which was a somewhat insane ([according to the author](https://metacpan.org/pod/Devel::Declare#WARNING)) attempt to implement keyword mechanics before the API that Syntax::Keyword::Try uses was made available. You generally want to avoid things based on Devel::Declare (and MooseX::Declare that uses it) wherever possible.

**Comment by kablamo** [comment]
I'm going to close this now.  Thanks for your help everyone.
